import { Inter, Josefin_Sans, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"], variable:'--inter' });
const josefin = Josefin_Sans({ subsets: ["latin"], variable: '--josefin' });
const poppins = Poppins({ subsets: ["latin"],
  weight:['300', '400', '500', '600', '700'],
variable: '--poppins' });

export const metadata = {
  title: "3dSetupBuilder",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${josefin.variable} ${poppins.variable}`}>
      <body>
        <main className="overflow-hidden">
          <Navbar/>
        {children}
        <Footer/>
        </main>
      </body>
    </html>
  );
}